# from math import pi as число_пи
# print(число_пи)
# n = int(input())
# print(int(n // 3))
# # В гостях у бабушки
# n = int(input('Укажите количество квартир на этаже '))
# k = int(input('Введите номер квартиры '))
# floor = k // n + bool(k % n)
# print(floor)
# n = int(input('Введите номер последней квартиры на первом этаже '))
# k = int(input('Введите номер квартиры бабушки '))
# c = int(input('Введите количество этажей в доме '))
# floor = k // n + bool(k % n)
# gate = floor // c + bool(floor % c)
# print(gate, floor)
# h = int(input())
# m = int(input())
# print(12 - h, 60 - m)
# a = int(input())
# print(a & (a -1))
